CREATE DATABASE IF NOT EXISTS hidden_chapters;
USE hidden_chapters;

CREATE TABLE IF NOT EXISTS books (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    author VARCHAR(255) NOT NULL,
    genre VARCHAR(100),
    moods VARCHAR(255), 
    teaser TEXT,
    cover VARCHAR(500),
    buyLink TEXT,
    downloadLink TEXT
);

INSERT INTO books (id, title, author, genre, moods, teaser, cover, buyLink, downloadLink)
VALUES 
(1, 'The Midnight Library', 'Matt Haig', 'Fantasy Fiction', 'thought-provoking, hopeful', 'Between life and death there is a library, and within that library, the shelves go on forever. Every book provides a chance to try another life you could have lived.', 'https://m.media-amazon.com/images/I/71ls-I6A5KL.UF1000,1000_QL80_.jpg', 'https://www.goodreads.com/book/show/52578297-the-midnight-library?ac=1&from_search=true&qid=sB4N0IDdXf&rank=1', 'https://archive.org/details/the-midnight-library-by-matt-haig_202406'),
(2, 'Project Hail Mary', 'Andy Weir', 'Science Fiction', 'adventurous, humorous, sci-fi', 'A lone astronaut awakens on a mission to save humanity, with no memory of who he is or how he got there. His only companions are two corpses... and a friendly alien.', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1597695864i/54493401.jpg', 'https://www.goodreads.com/book/show/54493401-project-hail-mary?from_search=true&from_srp=true&qid=FmiwABDybo&rank=1', 'https://archive.org/download/project-mary-hail/Project%20Mary%20Hail.pdf'),
(3, 'The Silent Patient', 'Alex Michaelides', 'Thriller', 'mysterious, suspenseful', 'A famous painter shoots her husband and then never speaks another word. A psychotherapist is determined to unravel the mystery of her silence.', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1668782119i/40097951.jpg', 'https://www.goodreads.com/book/show/40097951-the-silent-patient?ref=nav_sb_ss_1_18', 'https://www.epub.pub/book/the-silent-patient-by-alex-michaelides'),
(4, 'Circe', 'Madeline Miller', 'Fantasy', 'mythological, empowering, fantasy', 'Born in the house of Helios, a strange child, neither powerful like her father nor alluring like her mother, discovers she possesses the power of witchcraft.', 'https://m.media-amazon.com/images/I/91c0yRVm+0L.UF1000,1000_QL80_.jpg', 'https://www.amazon.in/Circe-Sunday-Bestseller-Madeline-Miller-ebook/dp/B076ZRJQ8N', 'https://archive.org/details/2019-Circe'),
(5, 'Pride and Prejudice', 'Jane Austen', 'Classic Romance', 'romantic, classic', 'A story of the five Bennet sisters in Georgian England, as they navigate issues of marriage, morality, and misconceptions. It is a truth universally acknowledged...', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1681804503i/129915654.jpg', 'https://www.goodreads.com/book/show/129915654-pride-and-prejudice?ac=1&from_search=true&qid=NputgiWhXs&rank=1', 'https://www.gutenberg.org/files/1342/1342-h/1342-h.htm'),
(6, 'Dune', 'Frank Herbert', 'Science Fiction', 'epic, sci-fi, adventurous', 'Set on a desert planet, a noble family is thrust into a war for control of the most valuable asset in the galaxy: a spice that extends life and enhances consciousness.', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1555447414i/44767458.jpg', 'https://www.goodreads.com/book/show/44767458-dune?ref=nav_sb_ss_1_5', 'https://lit2talks.com/read_book.php?bookpath=5614'),
(7, 'The Song of Achilles', 'Madeline Miller', 'Historical Fiction', 'romantic, heartbreaking, mythological, tragedy', 'An exiled prince forms an inseparable bond with the golden hero Achilles. As the Trojan War looms, they are tested by fate, gods, and their own hearts.', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1357177533i/13623848.jpg', 'https://www.goodreads.com/book/show/13623848-the-song-of-achilles?ref=nav_sb_ss_1_20', 'https://ia802300.us.archive.org/5/items/sq_20211001/the-song-books.yossr.com).pdf'),
(8, 'Educated', 'Tara Westover', 'Memoir', 'inspiring, thought-provoking', 'A young girl, kept out of school, leaves her survivalist family and goes on to earn a PhD from Cambridge University, discovering the transformative power of education.', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1506026635i/35133922.jpg', 'https://www.goodreads.com/book/show/35133922-educated?ref=nav_sb_ss_1_8', 'https://archive.org/download/molana-muhammad-zakariyya-ke-aap-beeti.-vol-1-urdukutabkhanapk.blogspot/04-Jan-2021_Uploaded_Biography/Educated%20by%20Tara%20Westover_%28urdukutabkhanapk.blogspot%29.pdf'),
(9, 'The Seven Husbands of Evelyn Hugo', 'Taylor Jenkins Reid', 'Historical Fiction', 'dramatic, romantic, drama', 'A reclusive Old Hollywood movie icon decides to give a final interview to an unknown magazine reporter, revealing the secrets of her glamorous and scandalous life.', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1664458703i/32620332.jpg', 'https://www.goodreads.com/book/show/32620332-the-seven-husbands-of-evelyn-hugo?ref=nav_sb_ss_1_33', 'https://pdfnovel.com/wp-content/PDFNovel/The%20Seven%20Husbands%20of%20Evelyn%20Hugo-PDFnovel.pdf'),
(10, 'A Man Called Ove', 'Fredrik Backman', 'Contemporary Fiction', 'humorous, heartwarming, hopeful', 'He''s a curmudgeon with strict principles and a short fuse. But behind the cranky exterior is a story of love and loss, and his life is about to be turned upside down by a boisterous young family.', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1405259930i/18774964.jpg', 'https://www.goodreads.com/book/show/18774964-a-man-called-ove?ref=nav_sb_ss_1_16', 'https://therustyquill.wordpress.com/wp-content/uploads/2021/05/man-called-ove_-a-novel-a-fredrik-backman.pdf'),
(11, 'Gone Girl', 'Gillian Flynn', 'Thriller', 'suspenseful, mysterious', 'On the day of their fifth wedding anniversary, a woman disappears. Her husband becomes the prime suspect, but the truth is far more twisted than anyone can imagine.', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1554086139i/19288043.jpg', 'https://www.goodreads.com/book/show/19288043-gone-girl?from_search=true&from_srp=true&qid=geA2vuQHeC&rank=1', 'https://icrrd.com/public/media/15-05-2021-082725Gone-Girl-Gillian-Flynn.pdf'),
(12, 'Atomic Habits', 'James Clear', 'Non-Fiction', 'inspiring, self-help', 'An easy and proven way to build good habits and break bad ones. Learn how tiny changes can lead to remarkable results over time.', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1655988385i/40121378.jpg', 'https://www.goodreads.com/book/show/40121378-atomic-habits?ref=nav_sb_ss_1_6', 'https://archive.org/download/atomic-habits-pdfdrive/Atomic%20habits%20%28%20PDFDrive%20%29.pdf'),
(13, 'It', 'Stephen King', 'Horror', 'scary, suspenseful', 'Seven children in a small town are terrorized by an evil entity that preys on their worst fears, clowning around in the sewers.', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1334416842i/830502.jpg', 'https://www.goodreads.com/book/show/830502.It?ref=nav_sb_ss_3_3', 'https://clicklibrary.files.wordpress.com/2018/09/it-by-stephen-king.pdf'),
(14, 'Haunting Adeline', 'H.D. Carlton', 'Dark Romance', 'dark romance, suspenseful, sexy', 'A woman moves into her family''s old manor and discovers the journals of her great-grandmother, who was stalked by a mysterious man. Soon, she finds herself the object of a new obsession.', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1628900532i/58763686.jpg', 'https://www.goodreads.com/book/show/58763686-haunting-adeline?ref=nav_sb_ss_1_16', 'https://archive.org/details/haunting-adeline'),
(15, 'Red, White & Royal Blue', 'Casey McQuiston', 'Contemporary Romance', 'romantic, humorous, bl romance', 'America''s First Son falls in love with a British prince, and their secret relationship could upend two nations and begs the question: can love save the world?', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1566742512i/41150487.jpg', 'https://www.goodreads.com/book/show/41150487-red-white-royal-blue?from_search=true&from_srp=true&qid=Vysj8GKoMz&rank=1', 'https://www.docdroid.net/WkLhOl2/red-white-royal-blue-pdf'),
(16, 'The Hobbit', 'J.R.R. Tolkien', 'Fantasy', 'adventurous, fantasy', 'A comfortable hobbit is swept into an epic quest to reclaim a stolen treasure from a fearsome dragon, alongside a company of dwarves.', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1546071216i/5907.jpg', 'https://www.goodreads.com/book/show/5907.The_Hobbit_or_There_and_Back_Again?ref=nav_sb_ss_1_10', 'https://rsd2-alert-durden-reading-room.weebly.com/uploads/6/7/1/6/6716949/the_hobbit_tolkien.pdf');

